// Generated by CoffeeScript 1.3.3

g4.module("g4.Item");

g4.defines(function() {
  return g4.Item = (function() {

    g4$Item.className = 'g4.Item';

    function g4$Item() {}

    g4$Item.prototype.scene = null;

    g4$Item.prototype.game = null;

    g4$Item.prototype.x = 0;

    g4$Item.prototype.y = 0;

    g4$Item.prototype.move = function(x, y) {
      this.x = x;
      this.y = y;
    };

    g4$Item.prototype.onCreate = function() {};

    g4$Item.prototype.onDestroy = function() {};

    g4$Item.prototype.onUpdate = function(delta) {};

    g4$Item.prototype.onDraw = function(ctx) {};

    return g4$Item;

  })();
});
