// Generated by CoffeeScript 1.3.1
var g4, r,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

console.log("---");

g4 = {};

g4.Object = (function() {

  g4$Object.className = 'g4.Object';

  function g4$Object(o) {
    var k, v;
    if (typeof o === "object") {
      for (k in o) {
        v = o[k];
        this[k] = v;
      }
    }
    if (typeof this.init === "function") {
      this.init();
    }
  }

  g4$Object.prototype.init = function() {};

  return g4$Object;

})();

g4.Font = (function(_super) {

  __extends(g4$Font, _super);

  g4$Font.className = 'g4.Font';

  function g4$Font() {
    return g4$Font.__super__.constructor.apply(this, arguments);
  }

  g4$Font.Style = {
    Normal: "Normal",
    Bold: "Bold",
    Italic: "Italic"
  };

  g4$Font.prototype.name = "";

  g4$Font.prototype.size = 10;

  g4$Font.prototype.style = g4$Font.Style.Normal;

  return g4$Font;

})(g4.Object);

g4.Text = (function(_super) {

  __extends(g4$Text, _super);

  g4$Text.className = 'g4.Text';

  function g4$Text() {
    return g4$Text.__super__.constructor.apply(this, arguments);
  }

  g4$Text.prototype.x = 0;

  g4$Text.prototype.y = 0;

  g4$Text.prototype.font = null;

  g4$Text.prototype.text = "";

  return g4$Text;

})(g4.Object);

g4.Rect = (function(_super) {

  __extends(g4$Rect, _super);

  g4$Rect.className = 'g4.Rect';

  function g4$Rect() {
    return g4$Rect.__super__.constructor.apply(this, arguments);
  }

  g4$Rect.prototype.x = 0;

  g4$Rect.prototype.y = 0;

  g4$Rect.prototype.width = 0;

  g4$Rect.prototype.height = 0;

  g4$Rect.prototype.text = null;

  return g4$Rect;

})(g4.Object);

r = new g4.Rect({
  x: 10,
  y: 10,
  width: 100,
  height: 100,
  text: new g4.Text({
    x: 5,
    y: 5,
    font: new g4.Font({
      name: "Arial",
      size: 20,
      style: g4.Font.Style.Bold
    })
  }),
  init: function() {
    return console.log(this.text.font.style);
  }
});

console.dir(r);

console.log(g4.Rect.name);
